apiVersion: v1
kind: ServiceAccount
metadata:
  name: mirador-service-python
  namespace: mirador
  labels:
    app.kubernetes.io/name: mirador-service-python
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: mirador
automountServiceAccountToken: false  # the deployment doesn't talk to k8s API
